# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8740c9958ad2e0fc24c6959dc04a2bceb0c5705032f47cc7305b8c996700ac6fd724a1e3af47fc68a10d88d21f22410dd70d701f5a2b99faac50a5c1e73dfa28

test:
  secret_key_base: 462b7e3277e0aea3a5ce6045a50d8f9f5e9e72e2fcb641312c950ed89fdb69bddfe9a5f729ec8ba1e3788ff6980f0059db7030e6bc0ab485372972ce1906c685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
